export enum UserError {
    DUPLICATED_EMAIL,
    USER_NOT_FOUND,
    USERNAME_OR_PASSWORD_INCORRECT,
    UNKNOWN_ERROR,
    BASKET_NOT_FOUND,
    PRODUCT_NOT_FOUND_FROM_BASKET,
    USER_ALREADY_EXISTS,
    ADDRESS_NOT_FOUND,
    ACTIVE_ADDRESS_NOT_FOUND,
    PRODUCT_ALREADY_EXISTS
}
